version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    container_name: sbz_database
    environment:
      - MYSQL_DATABASE=workoutdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
